---
title: "Benchmark - full analysis"
author: "Analyses author: Jakub Kubiś"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

\




```{r  include=FALSE}
library(ggplot2)


data <- read.csv('test_stats/full.csv')


```


\

#### Detected cells populations

```{r   include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}



df_long <- reshape2::melt(data[,c("test", "All_populations", "Quality_populations")], id.vars = "test", variable.name = "category", value.name = "values")


df_long$category <- sub("_", " ", df_long$category)

# Tworzenie wykresu
populations <- ggplot(df_long, aes(x = test, y = values, fill = category)) +
                geom_bar(stat = "identity", position = "dodge") +
                labs(x = "Tested tools",
                     y = "Number of populations") +
                theme_minimal() +
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                scale_fill_manual(values = c("All populations" = "steelblue", "Quality populations" = "orange"))

populations

```



\

#### Memory usage by tested tools

```{r   include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}





mem <- ggplot(data, aes(x = test, y = total.memory, fill = test)) +
        geom_bar(stat = "identity") +
        labs(x = "Tessted tool", y = "Total memory usage [GB]") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")


mem


```

\

#### Time of work of tested tools



```{r   include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}


time <- ggplot(data, aes(x = test, y = time, fill = test)) +
        geom_bar(stat = "identity") +
        labs(x = "Tessted tool", y = "Total time [s]") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")


time
 

```


#### Particular benchmark analysis raports:


```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}


raport_list <- list.files(path = file.path(getwd(), 'particular_raports/'), pattern = "*benchmark", full.names = TRUE)

for (file in raport_list) {
  
  cat(sprintf("- [%s](%s)\n", sub('.html', '', sub('benchmark_', '', basename(file))), file.path('particular_raports', basename(file))))
}


```
